[package]
name = "p8_restaurant_review"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.9.9"

[dev-dependencies]
solana-program-test = "1.9.9"
solana-sdk = "1.9.9"
thiserror = "1.0.63"

[lib]
crate-type = ["cdylib", "lib"]
